version: 2.1
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:11.12

commands:
  build:
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build

jobs:
  now:
    <<: *defaults
    steps:
      - build
      - run:
          name: install now
          command: sudo npm install -g --unsafe-perm now
      - run:
          name: deploy
          command: |
            now -t ${ZEIT_TOKEN}
            now alias pavlog -t ${ZEIT_TOKEN}

workflows:
  deploy:
    jobs:
      - now:
          filters:
            branches:
              only: master
